@extends('layout.main')

@section('content')

<div class="container my-5">
    <h1>Home</h1>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ex eveniet, nobis, optio, a maxime odit facilis consequuntur laboriosam ipsa eos numquam eaque doloremque at sit nulla! Aut rerum incidunt id beatae accusantium adipisci eaque a? Deleniti ullam, provident alias quia voluptatem commodi repellat aliquam velit iste distinctio perspiciatis. Aperiam cumque vero a illo voluptates quod? Repellendus alias iste ullam consequatur, laudantium qui, dolore deserunt reiciendis vitae iure, maiores possimus illum omnis! Repellat, iusto eos cumque aspernatur aperiam porro a tempora dolorem cum exercitationem nam iste illum dicta commodi tenetur ipsum, soluta tempore saepe repellendus veritatis deleniti autem perferendis? Error numquam incidunt facilis iste expedita, voluptas debitis omnis veniam. Neque facilis fuga ea aut, nisi minus nulla iste accusantium in dolor ullam voluptatem vitae, delectus odit, consequatur corporis! Sint obcaecati doloremque at iusto dolorem facere eligendi, id porro. Molestiae maxime quaerat consectetur accusantium eligendi excepturi numquam et debitis. Nam et similique velit exercitationem animi necessitatibus quisquam repudiandae laudantium accusamus ex laborum amet nesciunt accusantium fugiat iure, recusandae cupiditate omnis officiis porro. Voluptas itaque quis, voluptatum quod sequi nulla hic totam laborum corrupti fuga et iste assumenda dignissimos nam dicta quae dolorem enim eveniet quia facere, fugit ullam provident veritatis laboriosam? Ea accusamus reprehenderit, tenetur quis ut officiis sequi officia dicta, consequuntur nostrum dolorum accusantium eius illum. Corrupti hic ab nobis commodi fuga nam suscipit facilis ad amet, numquam dolor cum quam totam, non aliquid ducimus quo, ullam neque harum corporis temporibus. Maiores expedita unde adipisci animi similique modi repudiandae alias, minus quod at numquam, cum amet laudantium eum fugit voluptates tenetur commodi! Maiores non ad consectetur? Libero quo, quos aspernatur in molestias et veritatis exercitationem commodi cupiditate eum modi animi quod doloribus officia molestiae sunt eius laboriosam cum? Sed explicabo voluptatum minima quas ex quae itaque dignissimos! Totam nobis sequi mollitia!</p>
</div>

@endsection
